import { StyleSheet } from "react-native";
import { COLORS, FontSize, Height, Width } from "../../constants";

export const styles = StyleSheet.create({
  list: {
    paddingLeft: 16,
    paddingRight: 4,
    paddingVertical: 8,
  },
  card: {
    width: Width(160),
    height: Height(250),
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginRight: 16,
    padding: 12,
    justifyContent: 'space-between',
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
    backgroundColor: '#fff',
    overflow: 'visible',
  },
  image: {
    width: '100%',
    height: 100,
    borderRadius: 8,
    marginTop: 10,
  },
  adBadge: {
    position: 'absolute',
    top: -6,
    left: 12,
    backgroundColor: '#FF6F61',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    zIndex: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  adBadgeText: {
    color: '#fff',
    fontSize: FontSize(10),
    fontFamily: 'Inter-Bold',
    letterSpacing: 0.5,
  },
  brandContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  brandText: {
    fontSize: FontSize(10),
    fontFamily: 'Inter-SemiBold',
    color: '#416F81',
    backgroundColor: '#E6F0F5',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: {
    fontSize: FontSize(10),
    fontFamily: 'Inter-SemiBold',
    color: '#333',
    marginLeft: 2,
    marginRight: 4,
  },
  reviewsText: {
    fontSize: FontSize(9),
    fontFamily: 'Inter-Regular',
    color: '#888',
  },
  title: {
    fontSize: FontSize(12),
    fontFamily: 'Inter-SemiBold',
    color: '#333',
    marginTop: 6,
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    flexWrap: 'wrap',
  },
  price: {
    fontSize: 14,
    color: '#2E6074',
    fontFamily: 'Inter-Bold',
    marginRight: 8,
  },
  originalPrice: {
    fontSize: 11,
    color: '#999',
    fontFamily: 'Inter-Regular',
    textDecorationLine: 'line-through',
    marginRight: 8,
  },
  discount: {
    fontSize: 11,
    color: '#34C759',
    fontFamily: 'Inter-Bold',
  },
  shopNowButton: {
    backgroundColor: '#2E6074',
    paddingVertical: 8,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#2E6074',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
    marginTop:Height(4)
  },
  shopNowText: {
    color: '#fff',
    fontSize: FontSize(12),
    fontFamily: 'Inter-SemiBold',
    letterSpacing: 0.3,
  },
  favoriteButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 20,
    padding: 6,
    zIndex: 2,
  },
});